#!/bin/bash

echo "Builing texter"
go build
echo "Installing texter"
sudo mv texter /usr/bin
wget https://github.com/fiorix/go-daemon/releases/download/v1.3/go-daemon_1.3_amd64.deb
sudo apt install ./go-daemon_1.3_amd64.deb
rm ./go-daemon_1.3_amd64.deb
echo
texter